name: ci/gh-actions/depends

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.2.3)'
        required: true
      info:
        description: 'Release information (changelog)'
        required: false
        default: 'No information provided.'
  push:
    paths-ignore:
      - 'docs/**'
      - '**/README.md'
      - '.github/workflows/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/README.md'
      - '.github/workflows/**'

env:
  APT_SET_CONF: |
        echo "Acquire::Retries \"3\";"         | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::http::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::ftp::Timeout \"120\";"  | sudo tee -a /etc/apt/apt.conf.d/80-custom
  CCACHE_SETTINGS: |
        ccache --max-size=150M
        ccache --set-config=compression=true
  USE_DEVICE_TREZOR_MANDATORY: ON
  
  # Set release tag: use dispatch 'version' if present, otherwise use git ref_name
  RELEASE_TAG: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || github.ref_name }}
  # Set release info: use dispatch 'info' if present, otherwise set a default
  RELEASE_INFO: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.info || 'Auto-generated release for ${{ github.ref_name }}' }}
  
jobs:
  build-cross:
    # RUNNER_OS FIX: Use the 'runner_os' from the matrix below
    runs-on: ${{ matrix.toolchain.runner_os }}
    env:
      CCACHE_TEMPDIR: /tmp/.ccache-temp
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - name: "RISCV 64bit"
            host: "riscv64-linux-gnu"
            packages: "python3 gperf g++-riscv64-linux-gnu"
            build_flags: ""
            runner_os: "ubuntu-22.04" # Default runner
          - name: "ARM v7"
            host: "arm-linux-gnueabihf"
            packages: "python3 gperf g++-arm-linux-gnueabihf"
            # ARMv7 FIX: Pass HOST_ flags for 'depends' build AND EXTRA_CMAKE_FLAGS for main project build
            build_flags: "HOST_CFLAGS='-march=armv7-a -mfpu=neon-vfpv4' HOST_CXXFLAGS='-march=armv7-a -mfpu=neon-vfpv4' EXTRA_CMAKE_FLAGS='-DCMAKE_C_FLAGS=\"-march=armv7-a -mfpu=neon-vfpv4\" -DCMAKE_CXX_FLAGS=\"-march=armv7-a -mfpu=neon-vfpv4\"'"
            runner_os: "ubuntu-22.04"
          - name: "ARM v8"
            host: "aarch64-linux-gnu"
            packages: "python3 gperf g++-aarch64-linux-gnu"
            build_flags: ""
            runner_os: "ubuntu-22.04"
          - name: "i686 Win"
            host: "i686-w64-mingw32"
            packages: "python3 g++-mingw-w64-i686"
            build_flags: ""
            runner_os: "ubuntu-22.04"
          - name: "i686 Linux"
            host: "i686-pc-linux-gnu"
            packages: "gperf cmake g++-multilib python3-zmq"
            build_flags: ""
            runner_os: "ubuntu-22.04"
          - name: "Win64"
            host: "x86_64-w64-mingw32"
            packages: "cmake python3 g++-mingw-w64-x86-64"
            build_flags: ""
            runner_os: "ubuntu-22.04"
          - name: "x86_64 Linux"
            host: "x86_64-unknown-linux-gnu"
            packages: "gperf cmake python3-zmq libdbus-1-dev libharfbuzz-dev"
            build_flags: ""
            runner_os: "ubuntu-22.04"
          - name: "Cross-Mac x86_64"
            # Corrected typo from x86_66 to x86_64
            host: "x86_64-apple-darwin" 
            packages: "cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python3-dev python3-setuptools-git"
            build_flags: ""
            runner_os: "ubuntu-22.04"
          - name: "Cross-Mac aarch64"
            host: "aarch64-apple-darwin"
            packages: "cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python3-dev python3-setuptools-git"
            build_flags: ""
            runner_os: "ubuntu-22.04"
          - name: "x86_64 Freebsd"
            host: "x86_64-unknown-freebsd"
            packages: "clang-8 gperf cmake python3-zmq libdbus-1-dev libharfbuzz-dev"
            build_flags: ""
            runner_os: "ubuntu-20.04" # RUNNER_OS_FIX: Use Ubuntu 20.04 which supports clang-8
              #          - name: "ARMv8 Android"
              #            host: "aarch66-linux-android"
              #            packages: "gperf cmake python3"
              #            build_flags: ""
              #            runner_os: "ubuntu-22.04"

    name: ${{ matrix.toolchain.name }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

# Most volatile cache
    - name: ccache
      uses: actions/cache@v4
      with:
        path: ~/.ccache
        key: ccache-${{ matrix.toolchain.host }}-${{ github.sha }}
        restore-keys: ccache-${{ matrix.toolchain.host }}-

# Less volatile cache
    - name: depends cache
      uses: actions/cache@v4
      with:
        path: contrib/depends/built
        key: depends-${{ matrix.toolchain.host }}-${{ hashFiles('contrib/depends/packages/*') }}
        restore-keys: |
          depends-${{ matrix.toolchain.host }}-${{ hashFiles('contrib/depends/packages/*') }}
          depends-${{ matrix.toolchain.host }}-

# Static cache
    - name: OSX SDK cache
      uses: actions/cache@v4
      with:
        path: contrib/depends/sdk-sources
        key: sdk-${{ matrix.toolchain.host }}-${{ matrix.toolchain.osx_sdk }}
        restore-keys: sdk-${{ matrix.toolchain.host }}-${{ matrix.toolchain.osx_sdk }}

    - name: set apt conf
      run: ${{env.APT_SET_CONF}}

    # This step is still needed, but will now run on ubuntu-20.04 for the FreeBSD job and succeed
    - name: install clang-8 repo
      if: ${{ matrix.toolchain.host == 'x86_64-unknown-freebsd' }}
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 8

    - name: install dependencies
      run: sudo apt update; sudo apt -y install build-essential libtool libssl-dev cmake autotools-dev automake pkg-config bsdmainutils curl git ca-certificates ccache ${{ matrix.toolchain.packages }}

    - name: prepare w64-mingw32
      if: ${{ matrix.toolchain.host == 'x86_64-w64-mingw32' || matrix.toolchain.host == 'i686-w64-mingw32' }}
      run: |
        sudo update-alternatives --set ${{ matrix.toolchain.host }}-g++ $(which ${{ matrix.toolchain.host }}-g++-posix)
        sudo update-alternatives --set ${{ matrix.toolchain.host }}-gcc $(which ${{ matrix.toolchain.host }}-gcc-posix)

    - name: build
      run: |
        ${{env.CCACHE_SETTINGS}}
        # Pass the build_flags from the matrix to the make command
        make depends target=${{ matrix.toolchain.host }} ${{ matrix.toolchain.build_flags }} -j2

    - uses: actions/upload-artifact@v4
      if: ${{ matrix.toolchain.host == 'x86_64-w64-mingw32' || matrix.toolchain.host == 'x86_64-apple-darwin' || matrix.toolchain.host == 'aarch64-apple-darwin' || matrix.toolchain.host == 'x86_64-unknown-linux-gnu' }}
      with:
        name: ${{ matrix.toolchain.name }}
        path: |
          /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/build/${{ matrix.toolchain.host }}/release/bin/salvium-wallet-*
          /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/build/${{ matrix.toolchain.host }}/release/bin/salviumd*

    - name: zip daemon & cli
      run: |
        # Use the RELEASE_TAG env var for the zip file name
        zip salvium-${{ env.RELEASE_TAG }}-${{ matrix.toolchain.host }}.zip /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/build/${{ matrix.toolchain.host }}/release/bin/salvium-wallet-rpc* /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/build/${{ matrix.toolchain.host }}/release/bin/salvium-wallet-cli* /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/build/${{ matrix.toolchain.host }}/release/bin/salviumd*
        ls -l

    - name: "Create GitHub Release and Upload Asset"
      uses: softprops/action-gh-release@v1
      with:
        # Use the determined tag (from dispatch input or git ref)
        tag_name: ${{ env.RELEASE_TAG }}
        # Use the release info from dispatch input or a default message
        body: ${{ env.RELEASE_INFO }}
        # The file to upload, created in the previous step
        files: ./salvium-${{ env.RELEASE_TAG }}-${{ matrix.toolchain.host }}.zip
        # Create as a draft release to avoid spamming
        draft: true
        # This allows the action to add assets to an existing release
        # (which will be created by the first job that gets here)
        prerelease: false 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

